language: node_js
node_js:
  - "0.10"

sudo: false
  
before_script:
  - npm install -g grunt-cli
  
install: npm install

env:
  global:
    - secure: Kq3Tcj/EBN7Ql+Of0vZ82csiIgWnO2UbBEwMBbtvYlbbV0TCBhYupC4WlzauXBr/cn1oFf9OIOwxTXyi8e6dur34YOfzbgYyK3f++3xN7bhOty7HETpoibPTCKguHy+SD4Ww4tVk+8+TjqlRXmOmhG0X+blNqluPeJPOz5OoO/q4Y+oUl5ldZv4MS9x61JaL2podjpNscY++tynbqaQFBuPx/TE4REOFUM+H6rp6ApWktD58GIE8hZnFMwc7HC86sVPDeuqcaJ0zInXGuchJsHNqtBiT1sqLPAI60YL2BZb0XDEdF8c0OgMJmrn2E39ZTqkP+3auHrXYZ7g3BfkniZFDt+x2wXQbohzxfx2tWgJ6a3PeTo7oA9iLtKF/zOmYA+z7m2bjNptUWjYdWss6LnEyoCAINei/8WWlr65e1F3uo0omKqdTGtkiGLDPWirc+aC6jRr13Z0WPu8VAL5LzftwKpAV4QxV/Ib7wXDWzgcI+45NnQErWuUbM/pS6gDCXJDwMUi7jaYBiBbZ8N6Z9Y8gONcr4dpm2b/ZTH+uQ9tc3ixC7ezBtEzO/FtR8ulYZNFHiOkGP4iZS1pvrJJ64XhXz+4ry80fLsV9h/WMDmtNHQop8LzMcpwCmpR4FyBR4vvIOCDL6J+Pat308F+uq6cLUFxd4izv45KdQgbA3dM=
    - secure: cwGUF07p9tQPKNVgklr7pKnmwX5pczEUbIrjzTXLocvTN9ZwI/D0DsTYqHr1V50RHEn3tHRWRd5XklyeE7tO/E7HG/6ZgQpO6VNn7uVnhs/KXWMOaSGDLmSCcDr8wvooW8vQFPDUylmHflN2JJTUwNH58NMOthOHQz5/iWafyUQNUnthgfBsFik8gExqRtpWjNbrfWWQIJpcL0B/vZ9KxzxCdtYrC0gJX0eYu3GGJUtZF0y+t2HFMViQOgX8ZpM8gLeWIQDY9LHvFPc3Jcn6/A4mCwTAfIhHvQeX8KyMWk3Vlt81qBhZdoraiKI4W0awKes1Q2fFYuoXN2K63xjd+UsLZBzXClsYD1r75U6LTV06bmeveuYZgSirocU3bkjRMTILG6c+wdlfDKXIwaz1lPpp1X6SHx8qgOVjGR5YDd143GqOkt3pTMD1TAfBAHBIVjzJ1bNZAN68rjVoyfKm9zfV1JjTYpwh8wI/S8V4p2zagZwoDE7ORtAdPzpx8AORUf/A78/ztZ+U9eSRS3XUfiKgqr1Qq/K3kOcscc2kYfRg/GDSpnowqIvGQj293ltKYUA3UjDoH6M8dmYdjGq7QBQuWqS5WlVEU8+56JHoxfvExWGCv69ASZLtGZKa26N9qWhzAirxPOHdSdqBTtPG9Do1Rm03WUyXpaxgCYmAQ5o=

addons:
  username: "virtyaluk"
  sauce_connect: true